import nineteenEightyFour from "../../images/product_images/FICTION - 1984.jpg";
import lifeOfPi from "../../images/product_images/FICTION - Life of Pi.jpg";
import lordOfTheFlies from "../../images/product_images/FICTION - Lord of the Flies.jpg";
import prideAndPrejudice from "../../images/product_images/FICTION - Pride and Prejudice.jpg";
import theAlchemist from "../../images/product_images/FICTION - The Alchemist.jpg";
import theBookThief from "../../images/product_images/FICTION - The Book Thief.jpg";
import catcherInTheRye from "../../images/product_images/FICTION - The Catcher in the Rye.jpg";
import greatGatsby from "../../images/product_images/FICTION - The Great Gatsby.jpg";
import kiteRunner from "../../images/product_images/FICTION - The Kite Runner.jpg";
import toKillAMockingbird from "../../images/product_images/FICTION - To Kill a Mockingbird.jpg";

import sapiens from "../../images/product_images/Non-Fiction - Sapiens A Brief History of Humankind.jpg";
import becoming from "../../images/product_images/Non-Fiction - Becoming.jpg";
import educated from "../../images/product_images/Non-Fiction - Educated.jpg";
import inColdBlood from "../../images/product_images/Non-Fiction - In Cold Blood.jpg";
import intoTheWild from "../../images/product_images/Non-Fiction - Into the Wild.jpg";
import quiet from "../../images/product_images/Non-Fiction - Quiet.jpg";
import diaryOfYoungGirl from "../../images/product_images/Non-Fiction - The Diary of a Young Girl.jpg";
import henriettaLacks from "../../images/product_images/Non-Fiction - The Immortal Life of Henrietta Lacks.jpg";
import wrightBrothers from "../../images/product_images/Non-Fiction - The Wright Brothers.jpg";
import unbroken from "../../images/product_images/Non-Fiction - Unbroken.jpg";

import historyPh from "../../images/product_images/History - The History of the Philippines.jpg";
import seventeen76 from "../../images/product_images/History - 1776.jpg";
import peoplesHistory from "../../images/product_images/History - A Peoples History of the United States.jpg";
import elFili from "../../images/product_images/History - El Filibusterismo.jpg";
import noli from "../../images/product_images/History - Noli Me Tangere.jpg";
import teamOfRivals from "../../images/product_images/History - Team of Rivals.jpg";
import gunsAtLastLight from "../../images/product_images/History - The Guns at Last Light.jpg";
import gunsOfAugust from "../../images/product_images/History - The Guns of August.jpg";
import riseAndFall from "../../images/product_images/History - The Rise and Fall of the Third Reich.jpg";
import silkRoads from "../../images/product_images/History - The Silk Roads.jpg";

import atomicHabits from "../../images/product_images/Self-Help - Atomic Habits.jpg";
import awakenGiant from "../../images/product_images/Self-Help - Awaken the Giant Within.jpg";
import deepWork from "../../images/product_images/Self-Help - Deep Work.jpg";
import grit from "../../images/product_images/Self-Help - Grit.jpg";
import winFriends from "../../images/product_images/Self-Help - How to Win Friends and Influence People.jpg";
import mindset from "../../images/product_images/Self-Help - Mindset.jpg";
import sevenHabits from "../../images/product_images/Self-Help - The 7 Habits of Highly Effective People.jpg";
import powerOfNow from "../../images/product_images/Self-Help - The Power of Now.jpg";
import subtleArt from "../../images/product_images/Self-Help - The Subtle Art of Not Giving a Fck.jpg";
import thinkGrowRich from "../../images/product_images/Self-Help - Think and Grow Rich.jpg";

import oxfordDictionary from "../../images/product_images/Education - Oxford English Dictionary.jpg";
import apaManual from "../../images/product_images/Education - APA Publication Manual.jpg";
import britannica from "../../images/product_images/Education - Encyclopedia Britannica.jpg";
import historyPsych from "../../images/product_images/Education - History of Psychology.jpg";
import howChildrenLearn from "../../images/product_images/Education - How Children Learn.jpg";
import merriam from "../../images/product_images/Education - Merriam.jpg";
import pedagogy from "../../images/product_images/Education - Pedagogy of the Oppressed.jpg";
import teachingTransgress from "../../images/product_images/Education - Teaching to Transgress.jpg";
import elementsStyle from "../../images/product_images/Education - The Elements of Style.jpg";
import eduResearch from "../../images/product_images/Education - Understanding Education Research.jpg";

import harryPotter from "../../images/product_images/Fantasy - Harry Potter and the Sorcerers Stone.jpg";
import dune from "../../images/product_images/Fantasy - Dune.jpg";
import endersGame from "../../images/product_images/Fantasy - Enders Game.jpg";
import foundation from "../../images/product_images/Fantasy - Foundation.jpg";
import readyPlayerOne from "../../images/product_images/Fantasy - Ready Player One.jpg";
import narnia from "../../images/product_images/Fantasy - The Chronicles of Narnia.jpg";
import hobbit from "../../images/product_images/Fantasy - The Hobbit.jpg";
import hungerGames from "../../images/product_images/Fantasy - The Hunger Games.jpg";
import lotr from "../../images/product_images/Fantasy - The Lord of the Rings.jpg";
import nameOfWind from "../../images/product_images/Fantasy - The Name of the Wind.jpg";

import richDad from "../../images/product_images/Business - Rich Dad Poor Dad.jpg";
import blueOcean from "../../images/product_images/Business - Blue Ocean Strategy.jpg";
import goodToGreat from "../../images/product_images/Business - Good to Great.jpg";
import principles from "../../images/product_images/Business - Principles.jpg";
import startWithWhy from "../../images/product_images/Business - Start with Why.jpg";
import leanStartup from "../../images/product_images/Business - The Lean Startup.jpg";
import psychMoney from "../../images/product_images/Business - The Psychology of Money.jpg";
import thinkingFast from "../../images/product_images/Business - Thinking, Fast and Slow.jpg";
import zeroToOne from "../../images/product_images/Business - Zero to One.jpg";

const Products = [
  // FICTION
  {
    id: 1,
    image: nineteenEightyFour,
    imageBack: nineteenEightyFour,
    price: "$15.99",
    type: "Fiction",
    series: "Fiction",
    name: "1984",
    brand: "George Orwell",
    author: "George Orwell",
    synopsis: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real.",
    quantity: 50,
    pages: "328",
    language: "English",
    productType: "Book",
    productName: "1984",
  },
  {
    id: 2,
    image: lifeOfPi,
    imageBack: lifeOfPi,
    price: "$14.50",
    type: "Fiction",
    series: "Fiction",
    name: "Life of Pi",
    brand: "Yann Martel",
    author: "Yann Martel",
    synopsis: "The son of a zookeeper, Pi Patel has an encyclopedic knowledge of animal behavior and a fervent love of stories.",
    quantity: 45,
    pages: "319",
    language: "English",
    productType: "Book",
    productName: "Life of Pi",
  },
  {
    id: 3,
    image: lordOfTheFlies,
    imageBack: lordOfTheFlies,
    price: "$12.99",
    type: "Fiction",
    series: "Fiction",
    name: "Lord of the Flies",
    brand: "William Golding",
    author: "William Golding",
    synopsis: "At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys.",
    quantity: 60,
    pages: "224",
    language: "English",
    productType: "Book",
    productName: "Lord of the Flies",
  },
  {
    id: 4,
    image: prideAndPrejudice,
    imageBack: prideAndPrejudice,
    price: "$10.99",
    type: "Fiction",
    series: "Fiction",
    name: "Pride and Prejudice",
    brand: "Jane Austen",
    author: "Jane Austen",
    synopsis: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language.",
    quantity: 40,
    pages: "279",
    language: "English",
    productType: "Book",
    productName: "Pride and Prejudice",
  },
  {
    id: 5,
    image: theAlchemist,
    imageBack: theAlchemist,
    price: "$16.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Alchemist",
    brand: "Paulo Coelho",
    author: "Paulo Coelho",
    synopsis: "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery.",
    quantity: 70,
    pages: "208",
    language: "English",
    productType: "Book",
    productName: "The Alchemist",
  },
  {
    id: 6,
    image: theBookThief,
    imageBack: theBookThief,
    price: "$13.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Book Thief",
    brand: "Markus Zusak",
    author: "Markus Zusak",
    synopsis: "It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will become busier still.",
    quantity: 35,
    pages: "552",
    language: "English",
    productType: "Book",
    productName: "The Book Thief",
  },
  {
    id: 7,
    image: catcherInTheRye,
    imageBack: catcherInTheRye,
    price: "$11.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Catcher in the Rye",
    brand: "J.D. Salinger",
    author: "J.D. Salinger",
    synopsis: "The 'hero-narrator' of the Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caufield.",
    quantity: 55,
    pages: "277",
    language: "English",
    productType: "Book",
    productName: "The Catcher in the Rye",
  },
  {
    id: 8,
    image: greatGatsby,
    imageBack: greatGatsby,
    price: "$14.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Great Gatsby",
    brand: "F. Scott Fitzgerald",
    author: "F. Scott Fitzgerald",
    synopsis: "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career.",
    quantity: 48,
    pages: "180",
    language: "English",
    productType: "Book",
    productName: "The Great Gatsby",
  },
  {
    id: 9,
    image: kiteRunner,
    imageBack: kiteRunner,
    price: "$15.50",
    type: "Fiction",
    series: "Fiction",
    name: "The Kite Runner",
    brand: "Khaled Hosseini",
    author: "Khaled Hosseini",
    synopsis: "The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father's servant.",
    quantity: 42,
    pages: "371",
    language: "English",
    productType: "Book",
    productName: "The Kite Runner",
  },
  {
    id: 10,
    image: toKillAMockingbird,
    imageBack: toKillAMockingbird,
    price: "$13.50",
    type: "Fiction",
    series: "Fiction",
    name: "To Kill a Mockingbird",
    brand: "Harper Lee",
    author: "Harper Lee",
    synopsis: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
    quantity: 50,
    pages: "281",
    language: "English",
    productType: "Book",
    productName: "To Kill a Mockingbird",
  },

  // NON-FICTION
  {
    id: 11,
    image: sapiens,
    imageBack: sapiens,
    price: "$22.00",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Sapiens: A Brief History of Humankind",
    brand: "Yuval Noah Harari",
    author: "Yuval Noah Harari",
    synopsis: "One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one—homo sapiens.",
    quantity: 30,
    pages: "443",
    language: "English",
    productType: "Book",
    productName: "Sapiens",
  },
  {
    id: 12,
    image: becoming,
    imageBack: becoming,
    price: "$19.99",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Becoming",
    brand: "Michelle Obama",
    author: "Michelle Obama",
    synopsis: "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world.",
    quantity: 60,
    pages: "448",
    language: "English",
    productType: "Book",
    productName: "Becoming",
  },
  {
    id: 13,
    image: educated,
    imageBack: educated,
    price: "$18.50",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Educated",
    brand: "Tara Westover",
    author: "Tara Westover",
    synopsis: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom.",
    quantity: 45,
    pages: "352",
    language: "English",
    productType: "Book",
    productName: "Educated",
  },
  {
    id: 14,
    image: inColdBlood,
    imageBack: inColdBlood,
    price: "$16.00",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "In Cold Blood",
    brand: "Truman Capote",
    author: "Truman Capote",
    synopsis: "A seminal work of modern journalism that created a new genre: the non-fiction novel.",
    quantity: 35,
    pages: "343",
    language: "English",
    productType: "Book",
    productName: "In Cold Blood",
  },
  {
    id: 15,
    image: intoTheWild,
    imageBack: intoTheWild,
    price: "$14.99",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Into the Wild",
    brand: "Jon Krakauer",
    author: "Jon Krakauer",
    synopsis: "In April 1992 a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley.",
    quantity: 50,
    pages: "224",
    language: "English",
    productType: "Book",
    productName: "Into the Wild",
  },
  {
    id: 16,
    image: quiet,
    imageBack: quiet,
    price: "$17.00",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Quiet",
    brand: "Susan Cain",
    author: "Susan Cain",
    synopsis: "The power of introverts in a world that can't stop talking.",
    quantity: 55,
    pages: "352",
    language: "English",
    productType: "Book",
    productName: "Quiet",
  },
  {
    id: 17,
    image: diaryOfYoungGirl,
    imageBack: diaryOfYoungGirl,
    price: "$12.50",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "The Diary of a Young Girl",
    brand: "Anne Frank",
    author: "Anne Frank",
    synopsis: "Discovered in the attic in which she spent the last years of her life, Anne Frank's remarkable diary has become a world classic.",
    quantity: 100,
    pages: "283",
    language: "English",
    productType: "Book",
    productName: "The Diary of a Young Girl",
  },
  {
    id: 18,
    image: henriettaLacks,
    imageBack: henriettaLacks,
    price: "$16.50",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "The Immortal Life of Henrietta Lacks",
    brand: "Rebecca Skloot",
    author: "Rebecca Skloot",
    synopsis: "Her name was Henrietta Lacks, but scientists know her as HeLa. She was a poor Southern tobacco farmer who worked the same land as her slave ancestors.",
    quantity: 40,
    pages: "381",
    language: "English",
    productType: "Book",
    productName: "The Immortal Life",
  },
  {
    id: 19,
    image: wrightBrothers,
    imageBack: wrightBrothers,
    price: "$18.00",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "The Wright Brothers",
    brand: "David McCullough",
    author: "David McCullough",
    synopsis: "The dramatic story-behind-the-story about the courageous brothers who taught the world how to fly.",
    quantity: 30,
    pages: "320",
    language: "English",
    productType: "Book",
    productName: "The Wright Brothers",
  },
  {
    id: 20,
    image: unbroken,
    imageBack: unbroken,
    price: "$15.50",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Unbroken",
    brand: "Laura Hillenbrand",
    author: "Laura Hillenbrand",
    synopsis: "A World War II story of survival, resilience, and redemption.",
    quantity: 50,
    pages: "473",
    language: "English",
    productType: "Book",
    productName: "Unbroken",
  },

  // HISTORY
  {
    id: 21,
    image: historyPh,
    imageBack: historyPh,
    price: "$25.00",
    type: "History",
    series: "History",
    name: "The History of the Philippines",
    brand: "Reynaldo Ileto",
    author: "Reynaldo Ileto",
    synopsis: "A comprehensive look into the rich and diverse history of the Philippines.",
    quantity: 25,
    pages: "340",
    language: "English",
    productType: "Book",
    productName: "History of Philippines",
  },
  {
    id: 22,
    image: seventeen76,
    imageBack: seventeen76,
    price: "$19.00",
    type: "History",
    series: "History",
    name: "1776",
    brand: "David McCullough",
    author: "David McCullough",
    synopsis: "In this masterful book, David McCullough tells the intensely human story of those who marched with General George Washington in the year of the Declaration of Independence.",
    quantity: 40,
    pages: "386",
    language: "English",
    productType: "Book",
    productName: "1776",
  },
  {
    id: 23,
    image: peoplesHistory,
    imageBack: peoplesHistory,
    price: "$21.00",
    type: "History",
    series: "History",
    name: "A People's History of the United States",
    brand: "Howard Zinn",
    author: "Howard Zinn",
    synopsis: "A brilliant and moving history of the American people from the point of view of those who have been exploited.",
    quantity: 35,
    pages: "729",
    language: "English",
    productType: "Book",
    productName: "A People's History",
  },
  {
    id: 24,
    image: elFili,
    imageBack: elFili,
    price: "$13.00",
    type: "History",
    series: "History",
    name: "El Filibusterismo",
    brand: "Jose Rizal",
    author: "Jose Rizal",
    synopsis: "The sequel to Noli Me Tangere, this novel offers a darker, more political tone in its critique of the Philippine colonial society.",
    quantity: 60,
    pages: "350",
    language: "English/Spanish",
    productType: "Book",
    productName: "El Filibusterismo",
  },
  {
    id: 25,
    image: noli,
    imageBack: noli,
    price: "$13.00",
    type: "History",
    series: "History",
    name: "Noli Me Tangere",
    brand: "Jose Rizal",
    author: "Jose Rizal",
    synopsis: "The novel that sparked the Philippine Revolution, exposing the inequities of the Spanish Catholic friars and the ruling government.",
    quantity: 60,
    pages: "480",
    language: "English/Spanish",
    productType: "Book",
    productName: "Noli Me Tangere",
  },
  {
    id: 26,
    image: teamOfRivals,
    imageBack: teamOfRivals,
    price: "$24.00",
    type: "History",
    series: "History",
    name: "Team of Rivals",
    brand: "Doris Kearns Goodwin",
    author: "Doris Kearns Goodwin",
    synopsis: "The political genius of Abraham Lincoln is revealed in this story of his presidency and his cabinet.",
    quantity: 25,
    pages: "916",
    language: "English",
    productType: "Book",
    productName: "Team of Rivals",
  },
  {
    id: 27,
    image: gunsAtLastLight,
    imageBack: gunsAtLastLight,
    price: "$22.00",
    type: "History",
    series: "History",
    name: "The Guns at Last Light",
    brand: "Rick Atkinson",
    author: "Rick Atkinson",
    synopsis: "The final volume of the Liberation Trilogy, covering the war in Western Europe from D-Day to the German surrender.",
    quantity: 30,
    pages: "896",
    language: "English",
    productType: "Book",
    productName: "The Guns at Last Light",
  },
  {
    id: 28,
    image: gunsOfAugust,
    imageBack: gunsOfAugust,
    price: "$20.00",
    type: "History",
    series: "History",
    name: "The Guns of August",
    brand: "Barbara W. Tuchman",
    author: "Barbara W. Tuchman",
    synopsis: "Selected by the Modern Library as one of the 100 best nonfiction books of all time, this is the classic history of the outbreak of World War I.",
    quantity: 30,
    pages: "511",
    language: "English",
    productType: "Book",
    productName: "The Guns of August",
  },
  {
    id: 29,
    image: riseAndFall,
    imageBack: riseAndFall,
    price: "$28.00",
    type: "History",
    series: "History",
    name: "The Rise and Fall of the Third Reich",
    brand: "William L. Shirer",
    author: "William L. Shirer",
    synopsis: "One of the most important and celebrated histories of the Nazi era.",
    quantity: 20,
    pages: "1249",
    language: "English",
    productType: "Book",
    productName: "Third Reich",
  },
  {
    id: 30,
    image: silkRoads,
    imageBack: silkRoads,
    price: "$21.50",
    type: "History",
    series: "History",
    name: "The Silk Roads",
    brand: "Peter Frankopan",
    author: "Peter Frankopan",
    synopsis: "A new history of the world, focusing on the East and the trade routes that connected civilizations.",
    quantity: 35,
    pages: "636",
    language: "English",
    productType: "Book",
    productName: "The Silk Roads",
  },

  // SELF-HELP
  {
    id: 31,
    image: atomicHabits,
    imageBack: atomicHabits,
    price: "$18.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "Atomic Habits",
    brand: "James Clear",
    author: "James Clear",
    synopsis: "No matter your goals, Atomic Habits offers a proven framework for improving--every day.",
    quantity: 100,
    pages: "320",
    language: "English",
    productType: "Book",
    productName: "Atomic Habits",
  },
  {
    id: 32,
    image: awakenGiant,
    imageBack: awakenGiant,
    price: "$17.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "Awaken the Giant Within",
    brand: "Tony Robbins",
    author: "Tony Robbins",
    synopsis: "Tony Robbins provides a step-by-step program teaching the fundamental lessons of self-mastery.",
    quantity: 50,
    pages: "544",
    language: "English",
    productType: "Book",
    productName: "Awaken the Giant",
  },
  {
    id: 33,
    image: deepWork,
    imageBack: deepWork,
    price: "$16.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "Deep Work",
    brand: "Cal Newport",
    author: "Cal Newport",
    synopsis: "Rules for focused success in a distracted world.",
    quantity: 45,
    pages: "296",
    language: "English",
    productType: "Book",
    productName: "Deep Work",
  },
  {
    id: 34,
    image: grit,
    imageBack: grit,
    price: "$18.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "Grit",
    brand: "Angela Duckworth",
    author: "Angela Duckworth",
    synopsis: "In this instant New York Times bestseller, Angela Duckworth shows anyone striving to succeed that the secret to outstanding achievement is not talent, but a special blend of passion and persistence she calls 'grit'.",
    quantity: 55,
    pages: "352",
    language: "English",
    productType: "Book",
    productName: "Grit",
  },
  {
    id: 35,
    image: winFriends,
    imageBack: winFriends,
    price: "$14.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "How to Win Friends and Influence People",
    brand: "Dale Carnegie",
    author: "Dale Carnegie",
    synopsis: "For more than sixty years the rock-solid, time-tested advice in this book has carried thousands of now famous people up the ladder of success.",
    quantity: 80,
    pages: "288",
    language: "English",
    productType: "Book",
    productName: "How to Win Friends",
  },
  {
    id: 36,
    image: mindset,
    imageBack: mindset,
    price: "$16.50",
    type: "Self-Help",
    series: "Self-Help",
    name: "Mindset",
    brand: "Carol S. Dweck",
    author: "Carol S. Dweck",
    synopsis: "The new psychology of success. How we can learn to fulfill our potential.",
    quantity: 60,
    pages: "320",
    language: "English",
    productType: "Book",
    productName: "Mindset",
  },
  {
    id: 37,
    image: sevenHabits,
    imageBack: sevenHabits,
    price: "$19.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "The 7 Habits of Highly Effective People",
    brand: "Stephen R. Covey",
    author: "Stephen R. Covey",
    synopsis: "A holistic, integrated, principle-centered approach for solving personal and professional problems.",
    quantity: 75,
    pages: "381",
    language: "English",
    productType: "Book",
    productName: "7 Habits",
  },
  {
    id: 38,
    image: powerOfNow,
    imageBack: powerOfNow,
    price: "$15.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "The Power of Now",
    brand: "Eckhart Tolle",
    author: "Eckhart Tolle",
    synopsis: "A guide to spiritual enlightenment. It takes you on an inspiring spiritual journey to find your true and deepest self.",
    quantity: 50,
    pages: "236",
    language: "English",
    productType: "Book",
    productName: "The Power of Now",
  },
  {
    id: 39,
    image: subtleArt,
    imageBack: subtleArt,
    price: "$16.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "The Subtle Art of Not Giving a F*ck",
    brand: "Mark Manson",
    author: "Mark Manson",
    synopsis: "A counterintuitive approach to living a good life.",
    quantity: 85,
    pages: "224",
    language: "English",
    productType: "Book",
    productName: "Subtle Art",
  },
  {
    id: 40,
    image: thinkGrowRich,
    imageBack: thinkGrowRich,
    price: "$12.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "Think and Grow Rich",
    brand: "Napoleon Hill",
    author: "Napoleon Hill",
    synopsis: "This book provides a philosophy of individual achievement that stimulates the mind.",
    quantity: 65,
    pages: "238",
    language: "English",
    productType: "Book",
    productName: "Think and Grow Rich",
  },

  // EDUCATION
  {
    id: 41,
    image: oxfordDictionary,
    imageBack: oxfordDictionary,
    price: "$30.00",
    type: "Education",
    series: "Education",
    name: "Oxford English Dictionary",
    brand: "Oxford University Press",
    author: "Oxford University Press",
    synopsis: "The ultimate authority on the English language.",
    quantity: 65,
    pages: "2200",
    language: "English",
    productType: "Book",
    productName: "Oxford Dictionary",
  },
  {
    id: 42,
    image: apaManual,
    imageBack: apaManual,
    price: "$35.00",
    type: "Education",
    series: "Education",
    name: "APA Publication Manual",
    brand: "APA",
    author: "American Psychological Association",
    synopsis: "The official guide to APA Style.",
    quantity: 60,
    pages: "428",
    language: "English",
    productType: "Book",
    productName: "APA Manual",
  },
  {
    id: 43,
    image: britannica,
    imageBack: britannica,
    price: "$150.00",
    type: "Education",
    series: "Education",
    name: "Encyclopedia Britannica",
    brand: "Britannica",
    author: "Encyclopedia Britannica",
    synopsis: "A comprehensive encyclopedia for all your reference needs.",
    quantity: 10,
    pages: "3000+",
    language: "English",
    productType: "Book",
    productName: "Britannica",
  },
  {
    id: 44,
    image: historyPsych,
    imageBack: historyPsych,
    price: "$45.00",
    type: "Education",
    series: "Education",
    name: "History of Psychology",
    brand: "David Hothersall",
    author: "David Hothersall",
    synopsis: "An overview of the history of psychology.",
    quantity: 30,
    pages: "600",
    language: "English",
    productType: "Book",
    productName: "History of Psychology",
  },
  {
    id: 45,
    image: howChildrenLearn,
    imageBack: howChildrenLearn,
    price: "$18.00",
    type: "Education",
    series: "Education",
    name: "How Children Learn",
    brand: "John Holt",
    author: "John Holt",
    synopsis: "A classic work on child education and learning.",
    quantity: 40,
    pages: "320",
    language: "English",
    productType: "Book",
    productName: "How Children Learn",
  },
  {
    id: 46,
    image: merriam,
    imageBack: merriam,
    price: "$25.00",
    type: "Education",
    series: "Education",
    name: "Merriam-Webster's Collegiate Dictionary",
    brand: "Merriam-Webster",
    author: "Merriam-Webster",
    synopsis: "America's best-selling dictionary.",
    quantity: 80,
    pages: "1664",
    language: "English",
    productType: "Book",
    productName: "Merriam-Webster Dictionary",
  },
  {
    id: 47,
    image: pedagogy,
    imageBack: pedagogy,
    price: "$22.00",
    type: "Education",
    series: "Education",
    name: "Pedagogy of the Oppressed",
    brand: "Paulo Freire",
    author: "Paulo Freire",
    synopsis: "One of the most foundational texts in critical pedagogy.",
    quantity: 35,
    pages: "192",
    language: "English",
    productType: "Book",
    productName: "Pedagogy of the Oppressed",
  },
  {
    id: 48,
    image: teachingTransgress,
    imageBack: teachingTransgress,
    price: "$24.00",
    type: "Education",
    series: "Education",
    name: "Teaching to Transgress",
    brand: "bell hooks",
    author: "bell hooks",
    synopsis: "Education as the practice of freedom.",
    quantity: 30,
    pages: "216",
    language: "English",
    productType: "Book",
    productName: "Teaching to Transgress",
  },
  {
    id: 49,
    image: elementsStyle,
    imageBack: elementsStyle,
    price: "$10.00",
    type: "Education",
    series: "Education",
    name: "The Elements of Style",
    brand: "Strunk & White",
    author: "William Strunk Jr. & E.B. White",
    synopsis: "The classic style manual.",
    quantity: 100,
    pages: "105",
    language: "English",
    productType: "Book",
    productName: "Elements of Style",
  },
  {
    id: 50,
    image: eduResearch,
    imageBack: eduResearch,
    price: "$55.00",
    type: "Education",
    series: "Education",
    name: "Understanding Education Research",
    brand: "Author",
    author: "Various",
    synopsis: "A comprehensive guide to understanding educational research methods.",
    quantity: 20,
    pages: "500",
    language: "English",
    productType: "Book",
    productName: "Education Research",
  },

  // FANTASY
  {
    id: 51,
    image: harryPotter,
    imageBack: harryPotter,
    price: "$19.99",
    type: "Fantasy",
    series: "Fantasy",
    name: "Harry Potter and the Sorcerer's Stone",
    brand: "J.K. Rowling",
    author: "J.K. Rowling",
    synopsis: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat.",
    quantity: 85,
    pages: "309",
    language: "English",
    productType: "Book",
    productName: "Harry Potter",
  },
  {
    id: 52,
    image: dune,
    imageBack: dune,
    price: "$18.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "Dune",
    brand: "Frank Herbert",
    author: "Frank Herbert",
    synopsis: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange.",
    quantity: 60,
    pages: "412",
    language: "English",
    productType: "Book",
    productName: "Dune",
  },
  {
    id: 53,
    image: endersGame,
    imageBack: endersGame,
    price: "$16.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "Ender's Game",
    brand: "Orson Scott Card",
    author: "Orson Scott Card",
    synopsis: "Andrew 'Ender' Wiggin thinks he is playing computer simulated war games; he is, in fact, engaged in something far more desperate.",
    quantity: 50,
    pages: "324",
    language: "English",
    productType: "Book",
    productName: "Ender's Game",
  },
  {
    id: 54,
    image: foundation,
    imageBack: foundation,
    price: "$17.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "Foundation",
    brand: "Isaac Asimov",
    author: "Isaac Asimov",
    synopsis: "The first novel in the Foundation Series. The Galactic Empire has reigned for twelve thousand years. Now it is dying.",
    quantity: 55,
    pages: "255",
    language: "English",
    productType: "Book",
    productName: "Foundation",
  },
  {
    id: 55,
    image: readyPlayerOne,
    imageBack: readyPlayerOne,
    price: "$18.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "Ready Player One",
    brand: "Ernest Cline",
    author: "Ernest Cline",
    synopsis: "In the year 2045, reality is an ugly place. The only time Wade Watts really feels alive is when he's jacked into the OASIS, a vast virtual world where most of humanity spends their days.",
    quantity: 40,
    pages: "374",
    language: "English",
    productType: "Book",
    productName: "Ready Player One",
  },
  {
    id: 56,
    image: narnia,
    imageBack: narnia,
    price: "$25.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "The Chronicles of Narnia",
    brand: "C.S. Lewis",
    author: "C.S. Lewis",
    synopsis: "Journeys to the end of the world, fantastic creatures, and epic battles between good and evil—what more could any reader ask for in one book?",
    quantity: 40,
    pages: "767",
    language: "English",
    productType: "Book",
    productName: "Chronicles of Narnia",
  },
  {
    id: 57,
    image: hobbit,
    imageBack: hobbit,
    price: "$14.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "The Hobbit",
    brand: "J.R.R. Tolkien",
    author: "J.R.R. Tolkien",
    synopsis: "In a hole in the ground there lived a hobbit.",
    quantity: 70,
    pages: "310",
    language: "English",
    productType: "Book",
    productName: "The Hobbit",
  },
  {
    id: 58,
    image: hungerGames,
    imageBack: hungerGames,
    price: "$15.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "The Hunger Games",
    brand: "Suzanne Collins",
    author: "Suzanne Collins",
    synopsis: "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts.",
    quantity: 80,
    pages: "374",
    language: "English",
    productType: "Book",
    productName: "The Hunger Games",
  },
  {
    id: 59,
    image: lotr,
    imageBack: lotr,
    price: "$30.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "The Lord of the Rings",
    brand: "J.R.R. Tolkien",
    author: "J.R.R. Tolkien",
    synopsis: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.",
    quantity: 35,
    pages: "1178",
    language: "English",
    productType: "Book",
    productName: "The Lord of the Rings",
  },
  {
    id: 60,
    image: nameOfWind,
    imageBack: nameOfWind,
    price: "$19.00",
    type: "Fantasy",
    series: "Fantasy",
    name: "The Name of the Wind",
    brand: "Patrick Rothfuss",
    author: "Patrick Rothfuss",
    synopsis: "The tale of Kvothe, from his childhood in a troupe of traveling players, to years spent as a near-feral orphan in a crime-ridden city, to his daringly brazen yet successful bid to enter a legendary school of magic.",
    quantity: 45,
    pages: "662",
    language: "English",
    productType: "Book",
    productName: "The Name of the Wind",
  },

  // BUSINESS
  {
    id: 61,
    image: richDad,
    imageBack: richDad,
    price: "$17.50",
    type: "Business",
    series: "Business",
    name: "Rich Dad Poor Dad",
    brand: "Robert Kiyosaki",
    author: "Robert Kiyosaki",
    synopsis: "Rich Dad Poor Dad is Robert's story of growing up with two dads...",
    quantity: 60,
    pages: "336",
    language: "English",
    productType: "Book",
    productName: "Rich Dad Poor Dad",
  },
  {
    id: 62,
    image: blueOcean,
    imageBack: blueOcean,
    price: "$28.00",
    type: "Business",
    series: "Business",
    name: "Blue Ocean Strategy",
    brand: "W. Chan Kim",
    author: "W. Chan Kim & Renee Mauborgne",
    synopsis: "How to Create Uncontested Market Space and Make the Competition Irrelevant.",
    quantity: 40,
    pages: "256",
    language: "English",
    productType: "Book",
    productName: "Blue Ocean Strategy",
  },
  {
    id: 63,
    image: goodToGreat,
    imageBack: goodToGreat,
    price: "$25.00",
    type: "Business",
    series: "Business",
    name: "Good to Great",
    brand: "Jim Collins",
    author: "Jim Collins",
    synopsis: "Why Some Companies Make the Leap... and Others Don't.",
    quantity: 35,
    pages: "300",
    language: "English",
    productType: "Book",
    productName: "Good to Great",
  },
  {
    id: 64,
    image: principles,
    imageBack: principles,
    price: "$30.00",
    type: "Business",
    series: "Business",
    name: "Principles",
    brand: "Ray Dalio",
    author: "Ray Dalio",
    synopsis: "Ray Dalio, one of the world's most successful investors and entrepreneurs, shares the unconventional principles that he's developed, refined, and used over the past forty years.",
    quantity: 30,
    pages: "592",
    language: "English",
    productType: "Book",
    productName: "Principles",
  },
  {
    id: 65,
    image: startWithWhy,
    imageBack: startWithWhy,
    price: "$16.00",
    type: "Business",
    series: "Business",
    name: "Start with Why",
    brand: "Simon Sinek",
    author: "Simon Sinek",
    synopsis: "How Great Leaders Inspire Everyone to Take Action.",
    quantity: 65,
    pages: "256",
    language: "English",
    productType: "Book",
    productName: "Start with Why",
  },
  {
    id: 66,
    image: leanStartup,
    imageBack: leanStartup,
    price: "$22.00",
    type: "Business",
    series: "Business",
    name: "The Lean Startup",
    brand: "Eric Ries",
    author: "Eric Ries",
    synopsis: "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses.",
    quantity: 50,
    pages: "336",
    language: "English",
    productType: "Book",
    productName: "The Lean Startup",
  },
  {
    id: 67,
    image: psychMoney,
    imageBack: psychMoney,
    price: "$18.00",
    type: "Business",
    series: "Business",
    name: "The Psychology of Money",
    brand: "Morgan Housel",
    author: "Morgan Housel",
    synopsis: "Timeless lessons on wealth, greed, and happiness.",
    quantity: 70,
    pages: "252",
    language: "English",
    productType: "Book",
    productName: "The Psychology of Money",
  },
  {
    id: 68,
    image: thinkingFast,
    imageBack: thinkingFast,
    price: "$19.00",
    type: "Business",
    series: "Business",
    name: "Thinking, Fast and Slow",
    brand: "Daniel Kahneman",
    author: "Daniel Kahneman",
    synopsis: "The major New York Times bestseller that changes the way we think about thinking.",
    quantity: 45,
    pages: "499",
    language: "English",
    productType: "Book",
    productName: "Thinking, Fast and Slow",
  },
  {
    id: 69,
    image: zeroToOne,
    imageBack: zeroToOne,
    price: "$20.00",
    type: "Business",
    series: "Business",
    name: "Zero to One",
    brand: "Peter Thiel",
    author: "Peter Thiel",
    synopsis: "Notes on Startups, or How to Build the Future.",
    quantity: 40,
    pages: "224",
    language: "English",
    productType: "Book",
    productName: "Zero to One",
  },
];

export default Products;
