import soymilkImage from "../../images/product_images/EXCITINGMACARON-Soymilk.png";
import greengrapeImage from "../../images/product_images/EXCITING MACARON - Green Grape.png";
import lycheeberryImage from "../../images/product_images/EXCITING MACARON - Lychee Berry.png";
import seasaltcoconutImage from "../../images/product_images/EXCITING MACARON - Sea Salt Coconut.png";
import toffeeImage from "../../images/product_images/EXCITING MACARON - Toffee.png";
import sesamebeanImage from "../../images/product_images/EXCITING MACARON - Sesame Bean.png";
import singleboxEMImage from "../../images/product_images/EXCITING MACARON SINGLE BOX CASE.png";
import wholesetEMImage from "../../images/product_images/EXCITING MACARON WHOLE SET CASE.png";
import wholesetEMFrontImage from "../../images/product_images/EXCITING MACARON COVER.png";
import chestnutImage from "../../images/product_images/EXCITING MACARON - Chestnut (Secret).png";
import babaImage from "../../images/product_images/HAVE A SEAT - Baba.png";
import dadaImage from "../../images/product_images/HAVE A SEAT - Dada.png";
import heheImage from "../../images/product_images/HAVE A SEAT - Hehe.png";
import ququImage from "../../images/product_images/HAVE A SEAT - Ququ.png";
import sisiImage from "../../images/product_images/HAVE A SEAT - Sisi.png";
import ziziImage from "../../images/product_images/HAVE A SEAT - Zizi.png";
import duoduoImage from "../../images/product_images/HAVE A SEAT - Duoduo (Secret).png";
import singleboxHASImage from "../../images/product_images/HAVE A SEAT SINGLE BOX CASE.png";
import wholesetHASImage from "../../images/product_images/HAVE A SEAT WHOLE SET CASE.png";
import wholesetHASFrontImage from "../../images/product_images/HAVE A SEAT COVER.png";
import happinessImage from "../../images/product_images/BIG INTO ENERGY - Happiness.png";
import hopeImage from "../../images/product_images/BIG INTO ENERGY - Hope.png";
import loveImage from "../../images/product_images/BIG INTO ENERGY - Love.png";
import loyaltyImage from "../../images/product_images/BIG INTO ENERGY - Loyalty.png";
import luckImage from "../../images/product_images/BIG INTO ENERGY - Luck.png";
import serenityImage from "../../images/product_images/BIG INTO ENERGY - Serenity.png";
import singleboxBIGImage from "../../images/product_images/BIG INTO ENERGY SINGLE BOX CASE.png";
import wholesetBIGImage from "../../images/product_images/BIG INTO ENERGY WHOLE SET CASE.png";
import wholesetBIGFrontImage from "../../images/product_images/BIG INTO ENERGY COVER.png";
import idImage from "../../images/product_images/BIG INTO ENERGY - Id (Secret).png";
import happyfactorImage from "../../images/product_images/COCA-COLA SERIES - Happy Factor.png";
import surpriseshakeImage from "../../images/product_images/COCA-COLA SERIES - Surprise Shake.png";
import singleboxCCImage from "../../images/product_images/COCA-COLA SERIES SINGLE BOX CASE.png";
// import wholesetCCImage from "../../images/product_images/COCA-COLA SERIES WHOLE SET CASE.png";
import mysteriousguestImage from "../../images/product_images/COCA-COLA SERIES - Mysterious Guest (Secret).png";
import closetosweetImage from "../../images/product_images/MOKOKO - Close to Sweet.png";
import fallintospringImage from "../../images/product_images/MOKOKO - Fall into Spring.png";
import magicofpumpkinImage from "../../images/product_images/MOKOKO - Magic of Pumpkin.png";
import thebluediamondImage from "../../images/product_images/MOKOKO - The Blue Diamond.png";
import twinklyfairytaleImage from "../../images/product_images/MOKOKO - Twinkly Fairy Tale.png";
import fallinwild1Image from "../../images/product_images/SPECIAL PENDANTS - Fall in Wild 1.png";
import fallinwild2Image from "../../images/product_images/SPECIAL PENDANTS - Fall in Wild 2.png";
import goodlucktoyou1Image from "../../images/product_images/SPECIAL PENDANTS - Good Luck to You 1.png";
import goodlucktoyou2Image from "../../images/product_images/SPECIAL PENDANTS - Good Luck to You 2.png";
import hidenseek1Image from "../../images/product_images/SPECIAL PENDANTS - Hide & Seek 1.png";
import hidenseek2Image from "../../images/product_images/SPECIAL PENDANTS - Hide & Seek 2.png";
import letscheckmatequeen1Image from "../../images/product_images/SPECIAL PENDANTS - Let's Checkmate Queen 1.png";
import letscheckmatequeen2Image from "../../images/product_images/SPECIAL PENDANTS - Let's Checkmate Queen 2.png";
import sittingpumpkin1Image from "../../images/product_images/SPECIAL PENDANTS - Sitting Pumpkin 1.png";
import sittingpumpkin2Image from "../../images/product_images/SPECIAL PENDANTS - Sitting Pumpkin 2.png";
import wingsoffortune1Image from "../../images/product_images/SPECIAL PENDANTS - Wings of Fortune 1.png";
import wingsoffortune2Image from "../../images/product_images/SPECIAL PENDANTS - Wings of Fortune 2.png";
import angelinclouds1Image from "../../images/product_images/ZIMOMO - Angel in Clouds 1.png";
import angelinclouds2Image from "../../images/product_images/ZIMOMO - Angel in Clouds 2.png";
import ifoundyou1Image from "../../images/product_images/ZIMOMO - I Found You 1.png";
import ifoundyou2Image from "../../images/product_images/ZIMOMO - I Found You 2.png";
import dawnImage from "../../images/product_images/L'IMPRESSIONNISME - Dawn.png";
import dewImage from "../../images/product_images/L'IMPRESSIONNISME - Dew.png";
import lightningImage from "../../images/product_images/L'IMPRESSIONNISME - Lightning.png";
import pondImage from "../../images/product_images/L'IMPRESSIONNISME - Pond.png";
import windflowerImage from "../../images/product_images/L'IMPRESSIONNISME - Windflower.png";
import amberImage from "../../images/product_images/L'IMPRESSIONNISME - Amber.png";
import blossomImage from "../../images/product_images/L'IMPRESSIONNISME - Blossom.png";
import mistImage from "../../images/product_images/L'IMPRESSIONNISME - Mist.png";
import teakwoodImage from "../../images/product_images/L'IMPRESSIONNISME - Teakwood.png";
import singleboxLIImage from "../../images/product_images/L'IMPRESSIONNISME SINGLE BOX CASE.png";
import wholesetLIImage from "../../images/product_images/L'IMPRESSIONNISME WHOLE SET CASE.png";
import wholesetLIFrontImage from "../../images/product_images/L'IMPRESSIONNISME COVER.png";
import inthegardenImage from "../../images/product_images/L'IMPRESSIONNISME - In the Garden (Secret).png";
import odetococoaImage from "../../images/product_images/WINTER SYMPHONY - Ode to Cocoa.png";
import partitaImage from "../../images/product_images/WINTER SYMPHONY - Partita.png";
import rhapsodyImage from "../../images/product_images/WINTER SYMPHONY - Rhapsody.png";
import rockonImage from "../../images/product_images/WINTER SYMPHONY - Rock On.png";
import songofsnowImage from "../../images/product_images/WINTER SYMPHONY - Song of Snow.png";
import wandererstuneImage from "../../images/product_images/WINTER SYMPHONY - Wanderer's Tune.png";
import singleboxWSImage from "../../images/product_images/WINTER SYMPHONY SINGLE BOX CASE.png";
import wholesetWSImage from "../../images/product_images/WINTER SYMPHONY WHOLE SET CASE.png";
import wholesetWSFrontImage from "../../images/product_images/WINTER SYMPHONY COVER.png";
import symphonyofwishesImage from "../../images/product_images/WINTER SYMPHONY - Symphony of Wishes (Secret).png";
import cocacolaBundleImage from "../../images/product_bundles/CocaCola_Bundle.png";
import dadababaBundleImage from "../../images/product_bundles/Dada_Baba_Bundle.png";
import dadagreengrapeBundleImage from "../../images/product_bundles/Dada_GreenGrape_Bundle.png";
import dadaheheBundleImage from "../../images/product_bundles/Dada_Hehe_Bundle.png";
import dadaququBundleImage from "../../images/product_bundles/Dada_Ququ_Bundle.png";
import dadaseasaltBundleImage from "../../images/product_bundles/Dada_SeaSalt_Bundle.png";
import dadasesameBundleImage from "../../images/product_bundles/Dada_Sesame_Bundle.png";
import dadasisiBundleImage from "../../images/product_bundles/Dada_Sisi_Bundle.png";
import dadasoymilkBundleImage from "../../images/product_bundles/Dada_Soymilk_Bundle.png";
import dadatoffeeBundleImage from "../../images/product_bundles/Dada_Toffee_Bundle.png";
import dadaziziBundleImage from "../../images/product_bundles/Dada_Zizi_Bundle.png";
import lycheebabaBundleImage from "../../images/product_bundles/Lychee_Baba_Bundle.png";
import lycheedadaBundleImage from "../../images/product_bundles/Lychee_Dada_Bundle.png";
import lycheegreengrapeBundleImage from "../../images/product_bundles/Lychee_GreenGrape_Bundle.png";
import lycheeheheBundleImage from "../../images/product_bundles/Lychee_Hehe_Bundle.png";
import lycheeququBundleImage from "../../images/product_bundles/Lychee_Ququ_Bundle.png";
import lycheeseasaltBundleImage from "../../images/product_bundles/Lychee_SeaSalt_Bundle.png";
import lycheesesameBundleImage from "../../images/product_bundles/Lychee_Sesame_Bundle.png";
import lycheesisiBundleImage from "../../images/product_bundles/Lychee_Sisi_Bundle.png";
import lycheesoymilkBundleImage from "../../images/product_bundles/Lychee_Soymilk_Bundle.png";
import lycheetoffeeBundleImage from "../../images/product_bundles/Lychee_Toffee_Bundle.png";
import lycheeziziBundleImage from "../../images/product_bundles/Lychee_Zizi_Bundle.png";
import singleboxCCTWOImage from "../../images/product_bundles/COCA_COLA_TWO_SINGLE_BOX_CASE.png";
import singleboxEMEMImage from "../../images/product_bundles/EM_EM_SINGLE_BOX_CASE.png";
import singleboxHASHASImage from "../../images/product_bundles/HAS_HAS_SINGLE_BOX_CASE.png";
import singleboxEMHASImage from "../../images/product_bundles/EM_HAS_SINGLE_BOX_CASE.png";

const Products = [
  {
    id: 1,
    image: soymilkImage,
    imageBack: singleboxEMImage,
    price: "$49.99",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, SINGLE BOX",
    name: "SOY MILK",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 2,
    image: greengrapeImage,
    imageBack: singleboxEMImage,
    price: "$49.99",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, SINGLE BOX",
    name: "GREEN GRAPE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 3,
    image: lycheeberryImage,
    imageBack: singleboxEMImage,
    price: "$49.99",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, SINGLE BOX",
    name: "LYCHEE BERRY",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 4,
    image: seasaltcoconutImage,
    imageBack: singleboxEMImage,
    price: "$49.99",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, SINGLE BOX",
    name: "SEA SALT COCONUT",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 5,
    image: toffeeImage,
    imageBack: singleboxEMImage,
    price: "$49.99",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, SINGLE BOX",
    name: "TOFFEE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 6,
    image: sesamebeanImage,
    imageBack: singleboxEMImage,
    price: "$49.99",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, SINGLE BOX",
    name: "SESAME BEAN",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 7,
    image: wholesetEMFrontImage,
    imageBack: wholesetEMImage,
    price: "$275.00",
    type: "THE MONSTERS",
    series: "EXCITING MACARON, WHOLE SET",
    name: "WHOLE SET",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 8,
    image: babaImage,
    imageBack: singleboxHASImage,
    price: "$42.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, SINGLE BOX",
    name: "BABA",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 9,
    image: dadaImage,
    imageBack: singleboxHASImage,
    price: "$42.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, SINGLE BOX",
    name: "DADA",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 10,
    image: heheImage,
    imageBack: singleboxHASImage,
    price: "$42.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, SINGLE BOX",
    name: "HEHE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 11,
    image: ququImage,
    imageBack: singleboxHASImage,
    price: "$42.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, SINGLE BOX",
    name: "QUQU",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 12,
    image: sisiImage,
    imageBack: singleboxHASImage,
    price: "$42.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, SINGLE BOX",
    name: "SISI",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 13,
    image: ziziImage,
    imageBack: singleboxHASImage,
    price: "$42.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, SINGLE BOX",
    name: "ZIZI",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 14,
    image: wholesetHASFrontImage,
    imageBack: wholesetHASImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "HAVE A SEAT, WHOLE SET",
    name: "WHOLE SET",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 15,
    image: happinessImage,
    imageBack: singleboxBIGImage,
    price: "$54.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, SINGLE BOX",
    name: "HAPPINESS",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 16,
    image: hopeImage,
    imageBack: singleboxBIGImage,
    price: "$54.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, SINGLE BOX",
    name: "HOPE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 17,
    image: loveImage,
    imageBack: singleboxBIGImage,
    price: "$54.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, SINGLE BOX",
    name: "LOVE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 18,
    image: loyaltyImage,
    imageBack: singleboxBIGImage,
    price: "$54.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, SINGLE BOX",
    name: "LOYALTY",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 19,
    image: luckImage,
    imageBack: singleboxBIGImage,
    price: "$54.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, SINGLE BOX",
    name: "LUCK",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 20,
    image: serenityImage,
    imageBack: singleboxBIGImage,
    price: "$54.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, SINGLE BOX",
    name: "SERENITY",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 21,
    image: wholesetBIGFrontImage,
    imageBack: wholesetBIGImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "BIG INTO ENERGY, WHOLE SET",
    name: "WHOLE SET",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 22,
    image: happyfactorImage,
    imageBack: singleboxCCImage,
    price: "$55.00",
    type: "THE MONSTERS",
    series: "COCA-COLA SERIES, SINGLE BOX",
    name: "HAPPY FACTOR",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 23,
    image: surpriseshakeImage,
    imageBack: singleboxCCImage,
    price: "$55.00",
    type: "THE MONSTERS",
    series: "COCA-COLA SERIES, SINGLE BOX",
    name: "SURPRISE SHAKE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 24,
    image: closetosweetImage,
    imageBack: closetosweetImage,
    price: "$179.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "CLOSE TO SWEET 38CM (DOLL)",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 25,
    image: fallintospringImage,
    imageBack: fallintospringImage,
    price: "$349.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "FALL INTO SPRING 38CM (DOLL)",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 26,
    image: magicofpumpkinImage,
    imageBack: magicofpumpkinImage,
    price: "$299.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "MAGIC OF PUMPKIN",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 27,
    image: thebluediamondImage,
    imageBack: thebluediamondImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "THE BLUE DIAMOND",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 28,
    image: twinklyfairytaleImage,
    imageBack: twinklyfairytaleImage,
    price: "$299.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "TWINKLY FAIRY TALE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 29,
    image: fallinwild1Image,
    imageBack: fallinwild2Image,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "SPECIAL PENDANTS, SINGLE BOX",
    name: "FALL IN WILD",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 30,
    image: goodlucktoyou1Image,
    imageBack: goodlucktoyou2Image,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "SPECIAL PENDANTS, SINGLE BOX",
    name: "GOODLUCK TO YOU",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 31,
    image: hidenseek1Image,
    imageBack: hidenseek2Image,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "SPECIAL PENDANTS, SINGLE BOX",
    name: "HIDE AND SEEK",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 32,
    image: letscheckmatequeen1Image,
    imageBack: letscheckmatequeen2Image,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "SPECIAL PENDANTS, SINGLE BOX",
    name: "LET'S CHECKMATE QUEEN",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 33,
    image: sittingpumpkin1Image,
    imageBack: sittingpumpkin2Image,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "SPECIAL PENDANTS, SINGLE BOX",
    name: "SITTING PUMPKIN",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 34,
    image: wingsoffortune1Image,
    imageBack: wingsoffortune2Image,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "SPECIAL PENDANTS, SINGLE BOX",
    name: "WINGS OF FORTUNE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 35,
    image: angelinclouds1Image,
    imageBack: angelinclouds2Image,
    price: "$299.00",
    type: "THE MONSTERS",
    series: "ZIMOMO, SINGLE BOX",
    name: "ANGELS IN CLOUD",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 36,
    image: ifoundyou1Image,
    imageBack: ifoundyou2Image,
    price: "$299.00",
    type: "THE MONSTERS",
    series: "ZIMOMO, SINGLE BOX",
    name: "I FOUND YOU",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 37,
    image: dawnImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "DAWN",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 38,
    image: dewImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "DEW",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 39,
    image: lightningImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "LIGHTNING",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 40,
    image: pondImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "POND",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 41,
    image: windflowerImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "WINDFLOWER",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 42,
    image: wholesetLIFrontImage,
    imageBack: wholesetLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, WHOLE SET",
    name: "WHOLE SET",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 43,
    image: odetococoaImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, SINGLE BOX",
    name: "ODE TO COCOA",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 44,
    image: partitaImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, SINGLE BOX",
    name: "PARTITA",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 45,
    image: rhapsodyImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, SINGLE BOX",
    name: "RHAPSODY",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 46,
    image: rockonImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, SINGLE BOX",
    name: "ROCK ON",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 47,
    image: songofsnowImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, SINGLE BOX",
    name: "SONG OF SNOW",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 48,
    image: wandererstuneImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, SINGLE BOX",
    name: "WANDERER'S TUNE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 49,
    image: wholesetWSFrontImage,
    imageBack: wholesetWSImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "WINTER SYMPHONY, WHOLE SET",
    name: "WHOLE SET",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 50,
    image: chestnutImage,
    imageBack: singleboxEMImage,
    price: "$194.00",
    type: "SECRET",
    series: "EXCITING MACARON SECRET, SINGLE BOX",
    name: "CHESTNUT COCOA",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 51,
    image: duoduoImage,
    imageBack: singleboxHASImage,
    price: "$245.00",
    type: "SECRET",
    series: "HAVE A SEAT SECRET, SINGLE BOX",
    name: "DUODUO",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 52,
    image: idImage,
    imageBack: singleboxBIGImage,
    price: "$245.00",
    type: "SECRET",
    series: "BIG INTO ENERGY SECRET, SINGLE BOX",
    name: "ID",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 53,
    image: mysteriousguestImage,
    imageBack: singleboxCCImage,
    price: "$245.00",
    type: "SECRET",
    series: "COCA-COLA SERIES SECRET, SINGLE BOX",
    name: "MYSTERIOUS GUEST",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 54,
    image: inthegardenImage,
    imageBack: singleboxLIImage,
    price: "$294.00",
    type: "SECRET",
    series: "L'IMPRESSIONNISME SECRET, SINGLE BOX",
    name: "IN THE GARDEN",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 55,
    image: symphonyofwishesImage,
    imageBack: singleboxWSImage,
    price: "$245.00",
    type: "SECRET",
    series: "WINTER SYMPHONY SECRET, SINGLE BOX",
    name: "SYMPHONY OF WISHES",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 56,
    image: amberImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "AMBER",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 57,
    image: blossomImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "BLOSSOM",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 58,
    image: mistImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "MIST",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },
  {
    id: 59,
    image: teakwoodImage,
    imageBack: singleboxLIImage,
    price: "$245.00",
    type: "THE MONSTERS",
    series: "L'IMPRESSIONNISME, SINGLE BOX",
    name: "TEAKWOOD",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "SKULLPANDA",
    productName: "SKULLPANDA",
  },

  //BUNDLE IDS
  {
    id: 60,
    image: cocacolaBundleImage,
    imageBack: singleboxCCTWOImage,
    price: "$109.00",
    type: "THE MONSTERS",
    series: "HAPPY FACTOR AND SURPRISE SHAKE BUNDLE, SINGLE BOX",
    name: "HAPPY FACTOR AND SURPRISE SHAKE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 61,
    image: lycheedadaBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$109.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND DADA SPECIAL BUNDLE, SINGLE BOX",
    name: "LYCHEE AND DADA BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 62,
    image: lycheesoymilkBundleImage,
    imageBack: singleboxEMEMImage,
    price: "$105.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "LYCHEE AND SOYMILK BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 63,
    image: lycheesesameBundleImage,
    imageBack: singleboxEMEMImage,
    price: "$105.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "LYCHEE AND SESAME BEAN BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 64,
    image: lycheegreengrapeBundleImage,
    imageBack: singleboxEMEMImage,
    price: "$105.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "LYCHEE AND GREEN GRAPE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 65,
    image: lycheetoffeeBundleImage,
    imageBack: singleboxEMEMImage,
    price: "$105.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "LYCHEE AND TOFFEE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 66,
    image: lycheeseasaltBundleImage,
    imageBack: singleboxEMEMImage,
    price: "$105.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "LYCHEE AND SEASALT COCONUT BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 67,
    image: lycheesisiBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$99.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "LYCHEE AND SISI BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 68,
    image: lycheeheheBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$99.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "LYCHEE AND HEHE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 69,
    image: lycheeziziBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$99.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "LYCHEE AND ZIZI BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 70,
    image: lycheebabaBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$99.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "LYCHEE AND BABA BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 71,
    image: lycheeququBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$99.00",
    type: "THE MONSTERS",
    series: "LYCHEE AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "LYCHEE AND QUQU BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 72,
    image: dadasisiBundleImage,
    imageBack: singleboxHASHASImage,
    price: "$90.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "DADA AND SISI BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 73,
    image: dadaheheBundleImage,
    imageBack: singleboxHASHASImage,
    price: "$90.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "DADA AND HEHE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 74,
    image: dadaziziBundleImage,
    imageBack: singleboxHASHASImage,
    price: "$90.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "DADA AND ZIZI BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 75,
    image: dadababaBundleImage,
    imageBack: singleboxHASHASImage,
    price: "$90.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "DADA AND BABA BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 76,
    image: dadaququBundleImage,
    imageBack: singleboxHASHASImage,
    price: "$90.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE HAVE A SEAT BUNDLE, SINGLE BOX",
    name: "DADA AND QUQU BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 77,
    image: dadasoymilkBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$95.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "DADA AND SOYMILK BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 78,
    image: dadasesameBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$95.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "DADA AND SESAME BEAN BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 79,
    image: dadagreengrapeBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$95.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "DADA AND GREEN GRAPE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 80,
    image: dadatoffeeBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$95.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "DADA AND TOFFEE BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 81,
    image: dadaseasaltBundleImage,
    imageBack: singleboxEMHASImage,
    price: "$95.00",
    type: "THE MONSTERS",
    series: "DADA AND ONE EXCITING MACARON BUNDLE, SINGLE BOX",
    name: "DADA AND SEASALT COCONUT BUNDLE",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 82,
    image: closetosweetImage,
    imageBack: closetosweetImage,
    price: "$179.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "CLOSE TO SWEET (PENDANT)",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
  {
    id: 83,
    image: fallintospringImage,
    imageBack: fallintospringImage,
    price: "$349.00",
    type: "THE MONSTERS",
    series: "MOKOKO, SINGLE BOX",
    name: "FALL INTO SPRING (PENDANT)",
    brand: "Pop Mart",
    productSize: "1 inch",
    material: "ABS/PVC",
    lining: "100% Cotton",
    productType: "LABUBU",
    productName: "THE MONSTERS",
  },
];

export default Products;
