import nineteenEightyFour from "../../images/product_images/FICTION - 1984.jpg";
import lifeOfPi from "../../images/product_images/FICTION - Life of Pi.jpg";
import lordOfTheFlies from "../../images/product_images/FICTION - Lord of the Flies.jpg";
import prideAndPrejudice from "../../images/product_images/FICTION - Pride and Prejudice.jpg";
import theAlchemist from "../../images/product_images/FICTION - The Alchemist.jpg";
import theBookThief from "../../images/product_images/FICTION - The Book Thief.jpg";
import catcherInTheRye from "../../images/product_images/FICTION - The Catcher in the Rye.jpg";
import greatGatsby from "../../images/product_images/FICTION - The Great Gatsby.jpg";
import kiteRunner from "../../images/product_images/FICTION - The Kite Runner.jpg";
import toKillAMockingbird from "../../images/product_images/FICTION - To Kill a Mockingbird.jpg";
import sapiens from "../../images/product_images/Non-Fiction - Sapiens A Brief History of Humankind.jpg";
import historyPh from "../../images/product_images/History - The History of the Philippines.jpg";
import atomicHabits from "../../images/product_images/Self-Help - Atomic Habits.jpg";
import oxfordDictionary from "../../images/product_images/Education - Oxford English Dictionary.jpg";
import harryPotter from "../../images/product_images/Fantasy - Harry Potter and the Sorcerers Stone.jpg";
import richDad from "../../images/product_images/Business - Rich Dad Poor Dad.jpg";


const Products = [
  {
    id: 1,
    image: nineteenEightyFour,
    imageBack: nineteenEightyFour,
    price: "$15.99",
    type: "Fiction",
    series: "Fiction",
    name: "1984",
    brand: "George Orwell", // Keeping for compatibility, but mainly using author
    author: "George Orwell",
    synopsis: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmare vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality.",
    quantity: 50,
    pages: "328",
    language: "English",
    productType: "Book",
    productName: "1984",
  },
  {
    id: 2,
    image: lifeOfPi,
    imageBack: lifeOfPi,
    price: "$14.50",
    type: "Fiction",
    series: "Fiction",
    name: "Life of Pi",
    brand: "Yann Martel",
    author: "Yann Martel",
    synopsis: "The son of a zookeeper, Pi Patel has an encyclopedic knowledge of animal behavior and a fervent love of stories. When Pi is sixteen, his family emigrates from India to North America aboard a Japanese cargo ship, along with their zoo animals heading for new homes.",
    quantity: 45,
    pages: "319",
    language: "English",
    productType: "Book",
    productName: "Life of Pi",
  },
  {
    id: 3,
    image: lordOfTheFlies,
    imageBack: lordOfTheFlies,
    price: "$12.99",
    type: "Fiction",
    series: "Fiction",
    name: "Lord of the Flies",
    brand: "William Golding",
    author: "William Golding",
    synopsis: "At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate. This far from civilization they can do anything they want. Anything.",
    quantity: 60,
    pages: "224",
    language: "English",
    productType: "Book",
    productName: "Lord of the Flies",
  },
  {
    id: 4,
    image: prideAndPrejudice,
    imageBack: prideAndPrejudice,
    price: "$10.99",
    type: "Fiction",
    series: "Fiction",
    name: "Pride and Prejudice",
    brand: "Jane Austen",
    author: "Jane Austen",
    synopsis: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work 'her own darling child' and its vivacious heroine, Elizabeth Bennet, 'as delightful a creature as ever appeared in print.'",
    quantity: 40,
    pages: "279",
    language: "English",
    productType: "Book",
    productName: "Pride and Prejudice",
  },
  {
    id: 5,
    image: theAlchemist,
    imageBack: theAlchemist,
    price: "$16.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Alchemist",
    brand: "Paulo Coelho",
    author: "Paulo Coelho",
    synopsis: "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations.",
    quantity: 70,
    pages: "208",
    language: "English",
    productType: "Book",
    productName: "The Alchemist",
  },
  {
    id: 6,
    image: theBookThief,
    imageBack: theBookThief,
    price: "$13.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Book Thief",
    brand: "Markus Zusak",
    author: "Markus Zusak",
    synopsis: "It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will become busier still. Liesel Meminger is a foster girl living outside of Munich, who scratches out a meager existence for herself by stealing when she encounters something she can’t resist–books.",
    quantity: 35,
    pages: "552",
    language: "English",
    productType: "Book",
    productName: "The Book Thief",
  },
  {
    id: 7,
    image: catcherInTheRye,
    imageBack: catcherInTheRye,
    price: "$11.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Catcher in the Rye",
    brand: "J.D. Salinger",
    author: "J.D. Salinger",
    synopsis: "The 'hero-narrator' of the Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caufield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days.",
    quantity: 55,
    pages: "277",
    language: "English",
    productType: "Book",
    productName: "The Catcher in the Rye",
  },
  {
    id: 8,
    image: greatGatsby,
    imageBack: greatGatsby,
    price: "$14.99",
    type: "Fiction",
    series: "Fiction",
    name: "The Great Gatsby",
    brand: "F. Scott Fitzgerald",
    author: "F. Scott Fitzgerald",
    synopsis: "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his new love for the beautiful Daisy Buchanan.",
    quantity: 48,
    pages: "180",
    language: "English",
    productType: "Book",
    productName: "The Great Gatsby",
  },
  {
    id: 9,
    image: kiteRunner,
    imageBack: kiteRunner,
    price: "$15.50",
    type: "Fiction",
    series: "Fiction",
    name: "The Kite Runner",
    brand: "Khaled Hosseini",
    author: "Khaled Hosseini",
    synopsis: "The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father's servant, The Kite Runner is a beautifully crafted novel set in a country that is in the process of being destroyed.",
    quantity: 42,
    pages: "371",
    language: "English",
    productType: "Book",
    productName: "The Kite Runner",
  },
  {
    id: 10,
    image: toKillAMockingbird,
    imageBack: toKillAMockingbird,
    price: "$13.50",
    type: "Fiction",
    series: "Fiction",
    name: "To Kill a Mockingbird",
    brand: "Harper Lee",
    author: "Harper Lee",
    synopsis: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960.",
    quantity: 50,
    pages: "281",
    language: "English",
    productType: "Book",
    productName: "To Kill a Mockingbird",
  },
  {
    id: 11,
    image: sapiens,
    imageBack: sapiens,
    price: "$22.00",
    type: "Non-Fiction",
    series: "Non-Fiction",
    name: "Sapiens: A Brief History of Humankind",
    brand: "Yuval Noah Harari",
    author: "Yuval Noah Harari",
    synopsis: "One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one—homo sapiens. What happened to the others? And what may happen to us? Yuval Noah Harari breaks the mold with this highly original book that begins about 70,000 years ago.",
    quantity: 30,
    pages: "443",
    language: "English",
    productType: "Book",
    productName: "Sapiens",
  },
  {
    id: 12,
    image: historyPh,
    imageBack: historyPh,
    price: "$25.00",
    type: "History",
    series: "History",
    name: "The History of the Philippines",
    brand: "Reynaldo Ileto", // Assuming author
    author: "Reynaldo Ileto",
    synopsis: "A comprehensive look into the rich and diverse history of the Philippines, identifying the political, social, and cultural threads that have shaped the archipelago into the nation it is today.",
    quantity: 25,
    pages: "340",
    language: "English",
    productType: "Book",
    productName: "History of Philippines",
  },
  {
    id: 13,
    image: atomicHabits,
    imageBack: atomicHabits,
    price: "$18.00",
    type: "Self-Help",
    series: "Self-Help",
    name: "Atomic Habits",
    brand: "James Clear",
    author: "James Clear",
    synopsis: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    quantity: 100,
    pages: "320",
    language: "English",
    productType: "Book",
    productName: "Atomic Habits",
  },
  {
    id: 14,
    image: oxfordDictionary,
    imageBack: oxfordDictionary,
    price: "$30.00",
    type: "Education",
    series: "Education",
    name: "Oxford English Dictionary",
    brand: "Oxford University Press",
    author: "Oxford University Press",
    synopsis: "The ultimate authority on the English language as it is spoken and written today. This dictionary includes over 350,000 words, phrases, and definitions, making it the most comprehensive single-volume dictionary available using the latest research from the Oxford English Dictionary.",
    quantity: 65,
    pages: "2200",
    language: "English",
    productType: "Book",
    productName: "Oxford Dictionary",
  },
  {
    id: 15,
    image: harryPotter,
    imageBack: harryPotter,
    price: "$19.99",
    type: "Fantasy",
    series: "Fantasy",
    name: "Harry Potter and the Sorcerer's Stone",
    brand: "J.K. Rowling",
    author: "J.K. Rowling",
    synopsis: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news.",
    quantity: 85,
    pages: "309",
    language: "English",
    productType: "Book",
    productName: "Harry Potter",
  },
  {
    id: 16,
    image: richDad,
    imageBack: richDad,
    price: "$17.50",
    type: "Business",
    series: "Business",
    name: "Rich Dad Poor Dad",
    brand: "Robert Kiyosaki",
    author: "Robert Kiyosaki",
    synopsis: "Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
    quantity: 60,
    pages: "336",
    language: "English",
    productType: "Book",
    productName: "Rich Dad Poor Dad",
  },
];

export default Products;
